### ISSUE TITLE
今日校园版本过低，请更新至最新版本

### ISSUE THREAD

**Issue by meethigher** [Itswag/cpdaily_submit#1]
大佬，我根据你这个，在模拟post提交之后，返回的结果是“今日校园版本过低，请更新至最新版本”，你有碰到这个问题吗？我在user-agent中修改版本号，也没用

**Comment by Itswag** [comment]
我这边是正常的，是不是因为你的app版本过低了

**Comment by Itswag** [comment]
> 大佬，我根据你这个，在模拟post提交之后，返回的结果是“今日校园版本过低，请更新至最新版本”，你有碰到这个问题吗？我在user-agent中修改版本号，也没用

我这边是正常的，建议你先抓包走一遍流程

**Comment by meethigher** [comment]
ok了，ok了，原来是发送请求的是，请求体里面的格式不对
