### ISSUE TITLE
关于MOD_AUTH_CAS跟Cpdaily-Extension

### ISSUE THREAD

**Issue by meethigher** [Itswag/cpdaily_submit#2]
大佬，还有一个问题。我用java模仿你这个，写了一下类似的功能。https://meethigher.top/blog/2020/cpdaily-automation/
博客备注上面打上参考你的程序了。

如果请求的时候，header中没有Cpdaily-Extension，或者cookie中MOD_AUTH_CAS不正确，都会提交失败。
这个Cpdaily-Extension只要设备不退出，就不会失效。
我昨天测试，这个MOD_AUTH_CAS六个小时就会失效。那MOD_AUTH_CAS失效的原因是啥子？如果他是个session的话，过期不访问会失效，那我如果一直定时访问，会不会永久有效了啊？

**Comment by Itswag** [comment]
> 大佬，还有一个问题。我用java模仿你这个，写了一下类似的功能。https://meethigher.top/blog/2020/cpdaily-automation/
> 博客备注上面打上参考你的程序了。
> 
> 如果请求的时候，header中没有Cpdaily-Extension，或者cookie中MOD_AUTH_CAS不正确，都会提交失败。
> 这个Cpdaily-Extension只要设备不退出，就不会失效。
> 我昨天测试，这个MOD_AUTH_CAS六个小时就会失效。那MOD_AUTH_CAS失效的原因是啥子？如果他是个session的话，过期不访问会失效，那我如果一直定时访问，会不会永久有效了啊？
> 

你可以看一下CAS单点登录的相关知识，一般接口里有续期操作的话，你定时访问是可以的，但是没必要啊，我们老师每天8点前发布，17点结束，每天9点定时执行一次脚本就ok了。当然，你在轮询时也可以判断一下身份验证是否有效，无效则重新登录账户获取。

**Comment by meethigher** [comment]
好的，我去看一下
