### ISSUE TITLE
请问抓包用的模拟器是哪个版本？

### ISSUE THREAD

**Issue by bcahlit** [Itswag/cpdaily_submit#3]
我的模拟器显示 已停止运行，从之前一个项目看你是用的老版本，我用3.5版本也是停止运行。不知道哪个版本合适？

**Comment by Itswag** [comment]
> 我的模拟器显示 已停止运行，从之前一个项目看你是用的老版本，我用3.5版本也是停止运行。不知道哪个版本合适？

提供一个参考的 绕过 ssl pinning机制的方法：使用逍遥安卓4.4.4模拟器，配合xposed框架，使用justtrustme模块，hook掉验证证书的函数即可抓包

**Comment by bcahlit** [comment]
> > 我的模拟器显示 已停止运行，从之前一个项目看你是用的老版本，我用3.5版本也是停止运行。不知道哪个版本合适？
> 
> 提供一个参考的 绕过 ssl pinning机制的方法：使用逍遥安卓4.4.4模拟器，配合xposed框架，使用justtrustme模块，hook掉验证证书的函数即可抓包

我看到了，，我安装的4.4 出现停止运行，或者无法安装。我看到你另一个项目下说降版本解决的。不知道最后用的那个版本，我已经用了3.3 3.0 2.7 3.6 3.5 5.3 都不能成功运行今日校园。。。

**Comment by bcahlit** [comment]
3.3 3.0 2.7 3.6 3.5 5.3 是逍遥模拟器的版本，2.7的安卓版本是4.2.2 其他都是4.4

**Comment by Itswag** [comment]
> > > 我的模拟器显示 已停止运行，从之前一个项目看你是用的老版本，我用3.5版本也是停止运行。不知道哪个版本合适？
> > 
> > 提供一个参考的 绕过 ssl pinning机制的方法：使用逍遥安卓4.4.4模拟器，配合xposed框架，使用justtrustme模块，hook掉验证证书的函数即可抓包
> 
> 我看到了，，我安装的4.4 出现停止运行，或者无法安装。我看到你另一个项目下说降版本解决的。不知道最后用的那个版本，我已经用了3.3 3.0 2.7 3.6 3.5 5.3 都不能成功运行今日校园。。。

说实话我也忘了，应该是几年前的一个版本

**Comment by meethigher** [comment]
> > > 我的模拟器显示 已停止运行，从之前一个项目看你是用的老版本，我用3.5版本也是停止运行。不知道哪个版本合适？
> > 
> > 
> > 提供一个参考的 绕过 ssl pinning机制的方法：使用逍遥安卓4.4.4模拟器，配合xposed框架，使用justtrustme模块，hook掉验证证书的函数即可抓包
> 
> 我看到了，，我安装的4.4 出现停止运行，或者无法安装。我看到你另一个项目下说降版本解决的。不知道最后用的那个版本，我已经用了3.3 3.0 2.7 3.6 3.5 5.3 都不能成功运行今日校园。。。

过来看看大佬的代码，我一开始也是用模拟器，但是模拟器太麻烦了。推荐使用自己手机root哦，root以后随便抓包，简直爽到翻~

**Comment by meethigher** [comment]
> 我的模拟器显示 已停止运行，从之前一个项目看你是用的老版本，我用3.5版本也是停止运行。不知道哪个版本合适？

是安装app的时候，app停止运行吗？这个不是模拟器的事，换个今日校园版本。我之前碰到过，我后来换成了今日校园8.0.6版本的，就ok了。好像是今日校园8.1.12以上版本都不支持安卓4.4.4的系统了

**Comment by bcahlit** [comment]
恩，我安卓10 的手机root xp框架也抓不到，后来用了一个老的安卓6.0的手机抓的。感觉已经没有什么问题了～ 谢谢回复。
